[package]
org = "isuranga_sandun"
name = "bal_fhir_validator"
version = "0.1.0"
distribution = "2201.12.0-20250228-201300-8d411a0f"

[build-options]
observabilityIncluded = true

[[dependency]]
org = "ballerinax"
name = "health.fhir.r4.validator"
version = "5.0.2"
repository = "local"

[[dependency]]
org = "ballerinax"
name = "health.fhir.r4.parser"
version = "6.0.2"
repository = "local"
